const Map<String, String> en = {
  'hello': 'Hello',
  'multipleLanguage': 'Multiple language',
  'task': 'Task',
  'add': 'Add',
  'language': 'Language',
  'about': 'About',
  'vietnam': 'Vietnamese',
  'english': 'English',
  'live_tasks': 'Live tasks',
  'done_tasks': 'Done tasks',
  'total_tasks': 'Total tasks',
  'report': 'Report',
  'efficiency': 'Efficiency',
  'home': 'Home',
  'deleted': 'Deleted',
  'tasks': 'Tasks',
  'new_task': 'New task',
  'done': 'Done',
  'add_to': 'Add to',
  'add_new': 'Add new',
  'completed': 'Completed',
  'add_todos': 'Add todos',
  'add_todos_successfully': 'Add todos successfully',
  'please_enter_your_todo_item': 'Please enter your todo item',
  'please_enter_title': 'Please enter your title',
  'task_created': 'Task created',
  'add_alram': 'Add alarm',
  'never': 'Never',
  'everyday': 'Everyday',
  'title': 'Title',
  'optional': 'Optional',
  'repeat': 'Repeat',
  'monday': 'Monday',
  'tuesday': 'Tuesday',
  'wednesday': 'Wednesday',
  'thursday': 'Thursday',
  'friday': 'Friday',
  'saturday': 'Saturday',
  'sunday': 'Sunday',
  'mon': 'Mon',
  'tue': 'Tue',
  'wed': 'Wed',
  'thu': 'Thu',
  'fri': 'Fri',
  'sat': 'Sat',
  'sun': 'Sun',
  'alarm': 'Alarm',
  'timer': 'Timer',
  'clock': 'Clock',
  'start': 'Start',
  'new_timer': 'New Timer',
  'pause': 'Pause',
  'resume': 'Resume',
  'cancel': 'Cancel',
};
