const Map<String, String> vi = {
  'hello': 'Xin chào',
  'multipleLanguage': 'Đa ngôn ngữ',
  'task': 'Công việc',
  'add': 'Thêm',
  'language': 'Ngôn ngữ',
  'about': 'Về ứng dụng',
  'vietnam': 'Tiếng Việt',
  'english': 'Tiếng Anh',
  'live_tasks': 'Đang làm',
  'done_tasks': 'Đã làm',
  'total_tasks': 'Tổng',
  'report': 'Thống kê',
  'efficiency': 'Hiệu suất',
  'home': 'Trang chủ',
  'deleted': 'Đã xóa',
  'tasks': 'Công việc',
  'new_task': 'Thêm mới',
  'done': 'Xong',
  'add_to': 'Thêm vào',
  'add_new': 'Thêm mới',
  'completed': 'Đã hoàn thành',
  'add_todos': 'Thêm mục tiêu',
  'add_todos_successfully': 'Thêm mục tiêu thành công',
  'please_enter_your_todo_item': 'Hãy thêm mục tiêu',
  'please_enter_title': 'Hãy thêm tên',
  'task_created': 'Đã tạo',
  'add_alram': 'Đặt nhắc nhở',
  'never': 'Không lặp',
  'everyday': 'Mỗi ngày',
  'title': 'Nội dung',
  'optional': 'Không bắt buộc',
  'repeat': 'Lặp lại',
  'monday': 'Thứ hai',
  'tuesday': 'Thứ ba',
  'wednesday': 'Thứ tư',
  'thursday': 'Thứ năm',
  'friday': 'Thứ sáu',
  'saturday': 'Thứ bảy',
  'sunday': 'Chủ nhật',
  'mon': 'Hai',
  'tue': 'Ba',
  'wed': 'Tư',
  'thu': 'Năm',
  'fri': 'Sáu',
  'sat': 'Bảy',
  'sun': 'CN',
  'alarm': 'Báo thức',
  'timer': 'Đếm giờ',
  'clock': 'Đồng hồ',
  'start': 'Bắt đầu',
  'new_timer': 'Đếm giờ',
  'pause': 'Tạm dừng',
  'resume': 'Tiếp tục',
  'cancel': 'Hủy',
  'todo_item_already_exist': 'Công việc đã tồn tại',
};
